//! CampaignHomebrewMonster Data Access Layer
//!
//! Database operations for campaign homebrew monsters.
//! Generated by the `homebrew_crud!` macro.

use crate::models::campaign::{
    CampaignHomebrewMonster, NewCampaignHomebrewMonster, UpdateCampaignHomebrewMonster,
};
use crate::schema::campaign_homebrew_monsters;

super::homebrew_crud::homebrew_crud! {
    table: campaign_homebrew_monsters,
    model: CampaignHomebrewMonster,
    new_model: NewCampaignHomebrewMonster<'_>,
    update_model: UpdateCampaignHomebrewMonster<'_>,
    singular: monster,
    plural: monsters
}
