//! CampaignHomebrewItem Data Access Layer
//!
//! Database operations for campaign homebrew items.
//! Generated by the `homebrew_crud!` macro.

use crate::models::campaign::{
    CampaignHomebrewItem, NewCampaignHomebrewItem, UpdateCampaignHomebrewItem,
};
use crate::schema::campaign_homebrew_items;

super::homebrew_crud::homebrew_crud! {
    table: campaign_homebrew_items,
    model: CampaignHomebrewItem,
    new_model: NewCampaignHomebrewItem<'_>,
    update_model: UpdateCampaignHomebrewItem<'_>,
    singular: item,
    plural: items
}
