//! CampaignHomebrewSpell Data Access Layer
//!
//! Database operations for campaign homebrew spells.
//! Generated by the `homebrew_crud!` macro.

use crate::models::campaign::{
    CampaignHomebrewSpell, NewCampaignHomebrewSpell, UpdateCampaignHomebrewSpell,
};
use crate::schema::campaign_homebrew_spells;

super::homebrew_crud::homebrew_crud! {
    table: campaign_homebrew_spells,
    model: CampaignHomebrewSpell,
    new_model: NewCampaignHomebrewSpell<'_>,
    update_model: UpdateCampaignHomebrewSpell<'_>,
    singular: spell,
    plural: spells
}
