// Auto-generated SRD test fixtures — do not edit manually
// Generated by scripts/extract-srd-fixtures.py
// SRD content is published under the OGL

/* eslint-disable @typescript-eslint/no-explicit-any */
export const srdBackgrounds: Record<string, any>[] = [
  {
    "basicRules": true,
    "entries": [
      {
        "items": [
          {
            "entry": "{@skill Insight}, {@skill Religion}",
            "name": "Skill Proficiencies:",
            "type": "item"
          },
          {
            "entry": "Two of your choice",
            "name": "Languages:",
            "type": "item"
          },
          {
            "entry": "A {@item holy symbol|phb} (a gift to you when you entered the priesthood), a prayer {@item book|phb} or prayer wheel, 5 sticks of incense, vestments, a set of {@item common clothes|phb}, and a belt {@item pouch|phb} containing 15 gp",
            "name": "Equipment:",
            "type": "item"
          }
        ],
        "style": "list-hang-notitle",
        "type": "list"
      },
      {
        "data": {
          "isFeature": true
        },
        "entries": [
          "As an acolyte, you command the respect of those who share your faith, and you can perform the religious ceremonies of your deity. You and your adventuring companions can expect to receive free healing and care at a temple, shrine, or other established presence of your faith, though you must provide any material components needed for spells. Those who share your religion will support you (but only you) at a modest lifestyle.",
          "You might also have ties to a specific temple dedicated to your chosen deity or pantheon, and you have a residence there. This could be the temple where you used to serve, if you remain on good terms with it, or a temple where you have found a new home. While near your temple, you can call upon the priests for assistance, provided the assistance you ask for is not hazardous and you remain in good standing with your temple."
        ],
        "name": "Feature: Shelter of the Faithful",
        "type": "entries"
      },
      {
        "entries": [
          "Acolytes are shaped by their experience in temples or other religious communities. Their study of the history and tenets of their faith and their relationships to temples, shrines, or hierarchies affect their mannerisms and ideals. Their flaws might be some hidden hypocrisy or heretical idea, or an ideal or bond taken to an extreme.",
          {
            "colLabels": [
              "d8",
              "Personality Trait"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I idolize a particular hero of my faith, and constantly refer to that person's deeds and example."
              ],
              [
                "2",
                "I can find common ground between the fiercest enemies, empathizing with them and always working toward peace."
              ],
              [
                "3",
                "I see omens in every event and action. The gods try to speak to us, we just need to listen."
              ],
              [
                "4",
                "Nothing can shake my optimistic attitude."
              ],
              [
                "5",
                "I quote (or misquote) sacred texts and proverbs in almost every situation."
              ],
              [
                "6",
                "I am tolerant (or intolerant) of other faiths and respect (or condemn) the worship of other gods."
              ],
              [
                "7",
                "I've enjoyed fine food, drink, and high society among my temple's elite. Rough living grates on me."
              ],
              [
                "8",
                "I've spent so long in the temple that I have little practical experience dealing with people in the outside world."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Ideal"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Tradition. The ancient traditions of worship and sacrifice must be preserved and upheld. (Lawful)"
              ],
              [
                "2",
                "Charity. I always try to help those in need, no matter what the personal cost. (Good)"
              ],
              [
                "3",
                "Change. We must help bring about the changes the gods are constantly working in the world. (Chaotic)"
              ],
              [
                "4",
                "Power. I hope to one day rise to the top of my faith's religious hierarchy. (Lawful)"
              ],
              [
                "5",
                "Faith. I trust that my deity will guide my actions. I have faith that if I work hard, things will go well. (Lawful)"
              ],
              [
                "6",
                "Aspiration. I seek to prove myself worthy of my god's favor by matching my actions against his or her teachings. (Any)"
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Bond"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I would die to recover an ancient relic of my faith that was lost long ago."
              ],
              [
                "2",
                "I will someday get revenge on the corrupt temple hierarchy who branded me a heretic."
              ],
              [
                "3",
                "I owe my life to the priest who took me in when my parents died."
              ],
              [
                "4",
                "Everything I do is for the common people."
              ],
              [
                "5",
                "I will do anything to protect the temple where I served."
              ],
              [
                "6",
                "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Flaw"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I judge others harshly, and myself even more severely."
              ],
              [
                "2",
                "I put too much trust in those who wield power within my temple's hierarchy."
              ],
              [
                "3",
                "My piety sometimes leads me to blindly trust those that profess faith in my god."
              ],
              [
                "4",
                "I am inflexible in my thinking."
              ],
              [
                "5",
                "I am suspicious of strangers and expect the worst of them."
              ],
              [
                "6",
                "Once I pick a goal, I become obsessed with it to the detriment of everything else in my life."
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Suggested Characteristics",
        "type": "entries"
      }
    ],
    "hasFluff": true,
    "languageProficiencies": [
      {
        "anyStandard": 2
      }
    ],
    "name": "Acolyte",
    "page": 127,
    "reprintedAs": [
      "Acolyte|XPHB"
    ],
    "skillProficiencies": [
      {
        "insight": true,
        "religion": true
      }
    ],
    "source": "PHB",
    "srd": true,
    "startingEquipment": [
      {
        "_": [
          {
            "displayName": "holy symbol (a gift to you when you entered the priesthood)",
            "item": "holy symbol|phb"
          },
          {
            "quantity": 5,
            "special": "sticks of incense"
          },
          {
            "special": "vestments"
          },
          "common clothes|phb",
          {
            "containsValue": 1500,
            "item": "pouch|phb"
          }
        ]
      },
      {
        "a": [
          {
            "displayName": "prayer book",
            "item": "book|phb"
          }
        ],
        "b": [
          {
            "special": "prayer wheel"
          }
        ]
      }
    ],
    "id": 46,
    "fluff": {
      "entries": [
        {
          "entries": [
            {
              "entries": [
                "You have spent your life in the service of a temple to a specific god or pantheon of gods. You act as an intermediary between the realm of the holy and the mortal world, performing sacred rites and offering sacrifices in order to conduct worshipers into the presence of the divine. You are not necessarily a cleric—performing sacred rites is not the same thing as channeling divine power.",
                "Choose a god, a pantheon of gods, or some other quasi-divine being, and work with your DM to detail the nature of your religious service. The Gods of the Multiverse section contains a sample pantheon, from the Forgotten Realms setting. Were you a lesser functionary in a temple, raised from childhood to assist the priests in the sacred rites? Or were you a high priest who suddenly experienced a call to serve your god in a different way? Perhaps you were the leader of a small cult outside of any established temple structure, or even an occult group that served a fiendish master that you now deny."
              ],
              "type": "entries"
            }
          ],
          "type": "entries"
        }
      ],
      "name": "Acolyte",
      "source": "PHB"
    }
  },
  {
    "basicRules": true,
    "entries": [
      {
        "items": [
          {
            "entry": "{@skill Deception}, {@skill Stealth}",
            "name": "Skill Proficiencies:",
            "type": "item"
          },
          {
            "entry": "One type of {@filter gaming set|items|source=phb|miscellaneous=mundane|type=gaming set}, {@item thieves' tools|phb}",
            "name": "Tool Proficiencies:",
            "type": "item"
          },
          {
            "entry": "A {@item crowbar|phb}, a set of dark {@item common clothes|phb} including a hood, and a belt {@item pouch|phb} containing 15 gp",
            "name": "Equipment:",
            "type": "item"
          }
        ],
        "style": "list-hang-notitle",
        "type": "list"
      },
      {
        "data": {
          "isFeature": true
        },
        "entries": [
          "You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals. You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you."
        ],
        "name": "Feature: Criminal Contact",
        "type": "entries"
      },
      {
        "entries": [
          "There are many kinds of criminals, and within a thieves' guild or similar criminal organization, individual members have particular specialties. Even criminals who operate outside of such organizations have strong preferences for certain kinds of crimes over others. Choose the role you played in your criminal life, or roll on the table below.",
          {
            "colLabels": [
              "d8",
              "Specialty"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Blackmailer"
              ],
              [
                "2",
                "Burglar"
              ],
              [
                "3",
                "Enforcer"
              ],
              [
                "4",
                "Fence"
              ],
              [
                "5",
                "Highway robber"
              ],
              [
                "6",
                "Hired killer"
              ],
              [
                "7",
                "Pickpocket"
              ],
              [
                "8",
                "Smuggler"
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Specialty",
        "type": "entries"
      },
      {
        "entries": [
          "Criminals might seem like villains on the surface, and many of them are villainous to the core. But some have an abundance of endearing, if not redeeming, characteristics. There might be honor among thieves, but criminals rarely show any respect for law or authority.",
          {
            "colLabels": [
              "d8",
              "Personality Trait"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I always have a plan for when things go wrong."
              ],
              [
                "2",
                "I am always calm, no matter what the situation. I never raise my voice or let my emotions control me."
              ],
              [
                "3",
                "The first thing I do in a new place is note the locations of everything valuable—or where such things could be hidden."
              ],
              [
                "4",
                "I would rather make a new friend than a new enemy."
              ],
              [
                "5",
                "I am incredibly slow to trust. Those who seem the fairest often have the most to hide."
              ],
              [
                "6",
                "I don't pay attention to the risks in a situation. Never tell me the odds."
              ],
              [
                "7",
                "The best way to get me to do something is to tell me I can't do it."
              ],
              [
                "8",
                "I blow up at the slightest insult."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Ideal"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Honor. I don't steal from others in the trade. (Lawful)"
              ],
              [
                "2",
                "Freedom. Chains are meant to be broken, as are those who would forge them. (Chaotic)"
              ],
              [
                "3",
                "Charity. I steal from the wealthy so that I can help people in need. (Good)"
              ],
              [
                "4",
                "Greed. I will do whatever it takes to become wealthy. (Evil)"
              ],
              [
                "5",
                "People. I'm loyal to my friends, not to any ideals, and everyone else can take a trip down the Styx for all I care. (Neutral)"
              ],
              [
                "6",
                "Redemption. There's a spark of good in everyone. (Good)"
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Bond"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I'm trying to pay off an old debt I owe to a generous benefactor."
              ],
              [
                "2",
                "My ill-gotten gains go to support my family."
              ],
              [
                "3",
                "Something important was taken from me, and I aim to steal it back."
              ],
              [
                "4",
                "I will become the greatest thief that ever lived."
              ],
              [
                "5",
                "I'm guilty of a terrible crime. I hope I can redeem myself for it."
              ],
              [
                "6",
                "Someone I loved died because of a mistake I made. That will never happen again."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Flaw"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "When I see something valuable, I can't think about anything but how to steal it."
              ],
              [
                "2",
                "When faced with a choice between money and my friends, I usually choose the money."
              ],
              [
                "3",
                "If there's a plan, I'll forget it. If I don't forget it, I'll ignore it."
              ],
              [
                "4",
                "I have a 'tell' that reveals when I'm lying."
              ],
              [
                "5",
                "I turn tail and run when things look bad."
              ],
              [
                "6",
                "An innocent person is in prison for a crime that I committed. I'm okay with that."
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Suggested Characteristics",
        "type": "entries"
      }
    ],
    "hasFluff": true,
    "name": "Criminal",
    "page": 129,
    "reprintedAs": [
      "Criminal|XPHB"
    ],
    "skillProficiencies": [
      {
        "deception": true,
        "stealth": true
      }
    ],
    "source": "PHB",
    "startingEquipment": [
      {
        "_": [
          "crowbar|phb",
          {
            "displayName": "dark common clothes including a hood",
            "item": "common clothes|phb"
          },
          {
            "containsValue": 1500,
            "item": "pouch|phb"
          }
        ]
      }
    ],
    "toolProficiencies": [
      {
        "anyGamingSet": 1,
        "thieves' tools": true
      }
    ],
    "id": 48,
    "fluff": {
      "entries": [
        {
          "entries": [
            {
              "entries": [
                "You are an experienced criminal with a history of breaking the law. You have spent a lot of time among other criminals and still have contacts within the criminal underworld. You're far closer than most people to the world of murder, theft, and violence that pervades the underbelly of civilization, and you have survived up to this point by flouting the rules and regulations of society."
              ],
              "type": "entries"
            }
          ],
          "type": "entries"
        }
      ],
      "name": "Criminal",
      "source": "PHB"
    }
  },
  {
    "basicRules": true,
    "entries": [
      {
        "items": [
          {
            "entry": "{@skill Animal Handling}, {@skill Survival}",
            "name": "Skill Proficiencies:",
            "type": "item"
          },
          {
            "entry": "One type of {@filter artisan's tools|items|source=phb|miscellaneous=mundane|type=artisan's tools}, {@filter vehicles (land)|items|source=phb;dmg|miscellaneous=mundane|type=vehicle (land)}",
            "name": "Tool Proficiencies:",
            "type": "item"
          },
          {
            "entry": "A set of {@filter artisan's tools|items|source=phb|miscellaneous=mundane|type=artisan's tools} (one of your choice), a {@item shovel|phb}, an {@item iron pot|phb}, a set of {@item common clothes|phb}, and a belt {@item pouch|phb} containing 10 gp",
            "name": "Equipment:",
            "type": "item"
          }
        ],
        "style": "list-hang-notitle",
        "type": "list"
      },
      {
        "data": {
          "isFeature": true
        },
        "entries": [
          "Since you come from the ranks of the common folk, you fit in among them with ease. You can find a place to hide, rest, or recuperate among other commoners, unless you have shown yourself to be a danger to them. They will shield you from the law or anyone else searching for you, though they will not risk their lives for you."
        ],
        "name": "Feature: Rustic Hospitality",
        "type": "entries"
      },
      {
        "entries": [
          "You previously pursued a simple profession among the peasantry, perhaps as a farmer, miner, servant, shepherd, woodcutter, or gravedigger. But something happened that set you on a different path and marked you for greater things. Choose or randomly determine a defining event that marked you as a hero of the people.",
          {
            "colLabels": [
              "d10",
              "Defining Event"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I stood up to a tyrant's agents."
              ],
              [
                "2",
                "I saved people during a natural disaster."
              ],
              [
                "3",
                "I stood alone against a terrible monster."
              ],
              [
                "4",
                "I stole from a corrupt merchant to help the poor."
              ],
              [
                "5",
                "I led a militia to fight off an invading army."
              ],
              [
                "6",
                "I broke into a tyrant's castle and stole weapons to arm the people."
              ],
              [
                "7",
                "I trained the peasantry to use farming implements as weapons against a tyrant's soldiers."
              ],
              [
                "8",
                "A lord rescinded an unpopular decree after I led a symbolic act of protest against it."
              ],
              [
                "9",
                "A celestial, fey, or similar creature gave me a blessing or revealed my secret origin."
              ],
              [
                "10",
                "Recruited into a lord's army, I rose to leadership and was commended for my heroism."
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Specialty",
        "type": "entries"
      },
      {
        "entries": [
          "A folk hero is one of the common people, for better or for worse. Most folk heroes look on their humble origins as a virtue, not a shortcoming, and their home communities remain very important to them.",
          {
            "colLabels": [
              "d8",
              "Personality Trait"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I judge people by their actions, not their words."
              ],
              [
                "2",
                "If someone is in trouble, I'm always ready to lend help."
              ],
              [
                "3",
                "When I set my mind to something, I follow through no matter what gets in my way."
              ],
              [
                "4",
                "I have a strong sense of fair play and always try to find the most equitable solution to arguments."
              ],
              [
                "5",
                "I'm confident in my own abilities and do what I can to instill confidence in others."
              ],
              [
                "6",
                "Thinking is for other people. I prefer action."
              ],
              [
                "7",
                "I misuse long words in an attempt to sound smarter."
              ],
              [
                "8",
                "I get bored easily. When am I going to get on with my destiny?"
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Ideal"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Respect. People deserve to be treated with dignity and respect. (Good)"
              ],
              [
                "2",
                "Fairness. No one should get preferential treatment before the law, and no one is above the law. (Lawful)"
              ],
              [
                "3",
                "Freedom. Tyrants must not be allowed to oppress the people. (Chaotic)"
              ],
              [
                "4",
                "Might. If I become strong, I can take what I want—what I deserve. (Evil)"
              ],
              [
                "5",
                "Sincerity. There's no good in pretending to be something I'm not. (Neutral)"
              ],
              [
                "6",
                "Destiny. Nothing and no one can steer me away from my higher calling. (Any)"
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Bond"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I have a family, but I have no idea where they are. One day, I hope to see them again."
              ],
              [
                "2",
                "I worked the land, I love the land, and I will protect the land."
              ],
              [
                "3",
                "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter."
              ],
              [
                "4",
                "My tools are symbols of my past life, and I carry them so that I will never forget my roots."
              ],
              [
                "5",
                "I protect those who cannot protect themselves."
              ],
              [
                "6",
                "I wish my childhood sweetheart had come with me to pursue my destiny."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Flaw"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "The tyrant who rules my land will stop at nothing to see me killed."
              ],
              [
                "2",
                "I'm convinced of the significance of my destiny, and blind to my shortcomings and the risk of failure."
              ],
              [
                "3",
                "The people who knew me when I was young know my shameful secret, so I can never go home again."
              ],
              [
                "4",
                "I have a weakness for the vices of the city, especially hard drink."
              ],
              [
                "5",
                "Secretly, I believe that things would be better if I were a tyrant lording over the land."
              ],
              [
                "6",
                "I have trouble trusting in my allies."
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Suggested Characteristics",
        "type": "entries"
      }
    ],
    "hasFluff": true,
    "name": "Folk Hero",
    "page": 131,
    "skillProficiencies": [
      {
        "animal handling": true,
        "survival": true
      }
    ],
    "source": "PHB",
    "startingEquipment": [
      {
        "_": [
          {
            "equipmentType": "toolArtisan"
          },
          "shovel|phb",
          "iron pot|phb",
          "common clothes|phb",
          {
            "containsValue": 1000,
            "item": "pouch|phb"
          }
        ]
      }
    ],
    "toolProficiencies": [
      {
        "anyArtisansTool": 1,
        "vehicles (land)": true
      }
    ],
    "id": 51,
    "fluff": {
      "entries": [
        {
          "entries": [
            {
              "entries": [
                "You come from a humble social rank, but you are destined for so much more. Already the people of your home village regard you as their champion, and your destiny calls you to stand against the tyrants and monsters that threaten the common folk everywhere."
              ],
              "type": "entries"
            }
          ],
          "type": "entries"
        }
      ],
      "name": "Folk Hero",
      "source": "PHB"
    }
  },
  {
    "basicRules": true,
    "entries": [
      {
        "items": [
          {
            "entry": "{@skill History}, {@skill Persuasion}",
            "name": "Skill Proficiencies:",
            "type": "item"
          },
          {
            "entry": "One type of {@filter gaming set|items|source=phb|miscellaneous=mundane|type=gaming set}",
            "name": "Tool Proficiencies:",
            "type": "item"
          },
          {
            "entry": "One of your choice",
            "name": "Languages:",
            "type": "item"
          },
          {
            "entry": "A set of {@item fine clothes|phb}, a {@item signet ring|phb}, a scroll of pedigree, and a purse containing 25 gp",
            "name": "Equipment:",
            "type": "item"
          }
        ],
        "style": "list-hang-notitle",
        "type": "list"
      },
      {
        "data": {
          "isFeature": true
        },
        "entries": [
          "Thanks to your noble birth, people are inclined to think the best of you. You are welcome in high society, and people assume you have the right to be wherever you are. The common folk make every effort to accommodate you and avoid your displeasure, and other people of high birth treat you as a member of the same social sphere. You can secure an audience with a local noble if you need to."
        ],
        "name": "Feature: Position of Privilege",
        "type": "entries"
      },
      {
        "entries": [
          "Nobles are born and raised to a very different lifestyle than most people ever experience, and their personalities reflect that upbringing. A noble title comes with a plethora of bonds—responsibilities to family, to other nobles (including the sovereign), to the people entrusted to the family's care, or even to the title itself. But this responsibility is often a good way to undermine a noble.",
          {
            "colLabels": [
              "d8",
              "Personality Trait"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "My eloquent flattery makes everyone I talk to feel like the most wonderful and important person in the world."
              ],
              [
                "2",
                "The common folk love me for my kindness and generosity."
              ],
              [
                "3",
                "No one could doubt by looking at my regal bearing that I am a cut above the unwashed masses."
              ],
              [
                "4",
                "I take great pains to always look my best and follow the latest fashions."
              ],
              [
                "5",
                "I don't like to get my hands dirty, and I won't be caught dead in unsuitable accommodations."
              ],
              [
                "6",
                "Despite my noble birth, I do not place myself above other folk. We all have the same blood."
              ],
              [
                "7",
                "My favor, once lost, is lost forever."
              ],
              [
                "8",
                "If you do me an injury, I will crush you, ruin your name, and salt your fields."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Ideal"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Respect. Respect is due to me because of my position, but all people regardless of station deserve to be treated with dignity. (Good)"
              ],
              [
                "2",
                "Responsibility. It is my duty to respect the authority of those above me, just as those below me must respect mine. (Lawful)"
              ],
              [
                "3",
                "Independence. I must prove that I can handle myself without coddling from my family. (Chaotic)"
              ],
              [
                "4",
                "Power. If I can attain more power, no one will tell me what to do. (Evil)"
              ],
              [
                "5",
                "Family. Blood runs thicker than water. (Any)"
              ],
              [
                "6",
                "Noble Obligation. It is my duty to protect and care for the people beneath me. (Good)"
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Bond"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I will face any challenge to win the approval of my family."
              ],
              [
                "2",
                "My house's alliance with another noble family must be sustained at all costs."
              ],
              [
                "3",
                "Nothing is more important than the other members of my family."
              ],
              [
                "4",
                "I am in love with the heir of a family that my family despises."
              ],
              [
                "5",
                "My loyalty to my sovereign is unwavering."
              ],
              [
                "6",
                "The common folk must see me as a hero of the people."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Flaw"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I secretly believe that everyone is beneath me."
              ],
              [
                "2",
                "I hide a truly scandalous secret that could ruin my family forever."
              ],
              [
                "3",
                "I too often hear veiled insults and threats in every word addressed to me, and I'm quick to anger."
              ],
              [
                "4",
                "I have an insatiable desire for carnal pleasures."
              ],
              [
                "5",
                "In fact, the world does revolve around me."
              ],
              [
                "6",
                "By my words and actions, I often bring shame to my family."
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Suggested Characteristics",
        "type": "entries"
      }
    ],
    "hasFluff": true,
    "languageProficiencies": [
      {
        "anyStandard": 1
      }
    ],
    "name": "Noble",
    "page": 135,
    "reprintedAs": [
      "Noble|XPHB"
    ],
    "skillProficiencies": [
      {
        "history": true,
        "persuasion": true
      }
    ],
    "source": "PHB",
    "startingEquipment": [
      {
        "_": [
          "fine clothes|phb",
          "signet ring|phb",
          {
            "special": "scroll of pedigree"
          },
          {
            "containsValue": 2500,
            "special": "purse"
          }
        ]
      }
    ],
    "toolProficiencies": [
      {
        "anyGamingSet": 1
      }
    ],
    "id": 54,
    "fluff": {
      "entries": [
        {
          "entries": [
            {
              "entries": [
                "You understand wealth, power, and privilege. You carry a noble title, and your family owns land, collects taxes, and wields significant political influence. You might be a pampered aristocrat unfamiliar with work or discomfort, a former merchant just elevated to the nobility, or a disinherited scoundrel with a disproportionate sense of entitlement. Or you could be an honest, hard-working landowner who cares deeply about the people who live and work on your land, keenly aware of your responsibility to them.",
                "Work with your DM to come up with an appropriate title and determine how much authority that title carries. A noble title doesn't stand on its own—it's connected to an entire family, and whatever title you hold, you will pass it down to your own children. Not only do you need to determine your noble title, but you should also work with the DM to describe your family and their influence on you.",
                "Is your family old and established, or was your title only recently bestowed? How much influence do they wield, and over what area? What kind of reputation does your family have among the other aristocrats of the region? How do the common people regard them?",
                "What's your position in the family? Are you the heir to the head of the family? Have you already inherited the title? How do you feel about that responsibility? Or are you so far down the line of inheritance that no one cares what you do, as long as you don't embarrass the family? How does the head of your family feel about your adventuring career? Are you in your family's good graces, or shunned by the rest of your family?",
                "Does your family have a coat of arms? An insignia you might wear on a signet ring? Particular colors you wear all the time? An animal you regard as a symbol of your line or even a spiritual member of the family?",
                "These details help establish your family and your title as features of the world of the campaign."
              ],
              "type": "entries"
            }
          ],
          "type": "entries"
        }
      ],
      "name": "Noble",
      "source": "PHB"
    }
  },
  {
    "basicRules": true,
    "entries": [
      {
        "items": [
          {
            "entry": "{@skill Arcana}, {@skill History}",
            "name": "Skill Proficiencies:",
            "type": "item"
          },
          {
            "entry": "Two of your choice",
            "name": "Languages:",
            "type": "item"
          },
          {
            "entry": "A {@item Ink (1-ounce bottle)|phb|bottle of black ink}, a quill, a small knife, a letter from a dead colleague posing a question you have not yet been able to answer, a set of {@item common clothes|phb}, and a belt {@item pouch|phb} containing 10 gp",
            "name": "Equipment:",
            "type": "item"
          }
        ],
        "style": "list-hang-notitle",
        "type": "list"
      },
      {
        "data": {
          "isFeature": true
        },
        "entries": [
          "When you attempt to learn or recall a piece of lore, if you do not know that information, you often know where and from whom you can obtain it. Usually, this information comes from a library, scriptorium, university, or a sage or other learned person or creature. Your DM might rule that the knowledge you seek is secreted away in an almost inaccessible place, or that it simply cannot be found. Unearthing the deepest secrets of the multiverse can require an adventure or even a whole campaign."
        ],
        "name": "Feature: Researcher",
        "type": "entries"
      },
      {
        "entries": [
          "To determine the nature of your scholarly training, roll a d8 or choose from the options in the table below.",
          {
            "colLabels": [
              "d8",
              "Field of Study"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Alchemist"
              ],
              [
                "2",
                "Astronomer"
              ],
              [
                "3",
                "Discredited academic"
              ],
              [
                "4",
                "Librarian"
              ],
              [
                "5",
                "Professor"
              ],
              [
                "6",
                "Researcher"
              ],
              [
                "7",
                "Wizard's apprentice"
              ],
              [
                "8",
                "Scribe"
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Specialty",
        "type": "entries"
      },
      {
        "entries": [
          "Sages are defined by their extensive studies, and their characteristics reflect this life of study. Devoted to scholarly pursuits, a sage values knowledge highly—sometimes in its own right, sometimes as a means toward other ideals.",
          {
            "colLabels": [
              "d8",
              "Personality Trait"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I use polysyllabic words that convey the impression of great erudition."
              ],
              [
                "2",
                "I've read every book in the world's greatest libraries—or I like to boast that I have."
              ],
              [
                "3",
                "I'm used to helping out those who aren't as smart as I am, and I patiently explain anything and everything to others."
              ],
              [
                "4",
                "There's nothing I like more than a good mystery."
              ],
              [
                "5",
                "I'm willing to listen to every side of an argument before I make my own judgment."
              ],
              [
                "6",
                "I... speak... slowly... when talking... to idiots,... which... almost... everyone... is... compared... to me."
              ],
              [
                "7",
                "I am horribly, horribly awkward in social situations."
              ],
              [
                "8",
                "I'm convinced that people are always trying to steal my secrets."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Ideal"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Knowledge. The path to power and self-improvement is through knowledge. (Neutral)"
              ],
              [
                "2",
                "Beauty. What is beautiful points us beyond itself toward what is true. (Good)"
              ],
              [
                "3",
                "Logic. Emotions must not cloud our logical thinking. (Lawful)"
              ],
              [
                "4",
                "No Limits. Nothing should fetter the infinite possibility inherent in all existence. (Chaotic)"
              ],
              [
                "5",
                "Power. Knowledge is the path to power and domination. (Evil)"
              ],
              [
                "6",
                "Self-Improvement. The goal of a life of study is the betterment of oneself. (Any)"
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Bond"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "It is my duty to protect my students."
              ],
              [
                "2",
                "I have an ancient text that holds terrible secrets that must not fall into the wrong hands."
              ],
              [
                "3",
                "I work to preserve a library, university, scriptorium, or monastery."
              ],
              [
                "4",
                "My life's work is a series of tomes related to a specific field of lore."
              ],
              [
                "5",
                "I've been searching my whole life for the answer to a certain question."
              ],
              [
                "6",
                "I sold my soul for knowledge. I hope to do great deeds and win it back."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Flaw"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I am easily distracted by the promise of information."
              ],
              [
                "2",
                "Most people scream and run when they see a demon. I stop and take notes on its anatomy."
              ],
              [
                "3",
                "Unlocking an ancient mystery is worth the price of a civilization."
              ],
              [
                "4",
                "I overlook obvious solutions in favor of complicated ones."
              ],
              [
                "5",
                "I speak without really thinking through my words, invariably insulting others."
              ],
              [
                "6",
                "I can't keep a secret to save my life, or anyone else's."
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Suggested Characteristics",
        "type": "entries"
      }
    ],
    "hasFluff": true,
    "languageProficiencies": [
      {
        "anyStandard": 2
      }
    ],
    "name": "Sage",
    "page": 137,
    "reprintedAs": [
      "Sage|XPHB"
    ],
    "skillProficiencies": [
      {
        "arcana": true,
        "history": true
      }
    ],
    "source": "PHB",
    "startingEquipment": [
      {
        "_": [
          "ink (1-ounce bottle)|phb",
          {
            "special": "quill"
          },
          {
            "special": "small knife"
          },
          {
            "special": "letter from a dead colleague posing a question you have not yet been able to answer"
          },
          "common clothes|phb",
          {
            "containsValue": 1000,
            "item": "pouch|phb"
          }
        ]
      }
    ],
    "id": 56,
    "fluff": {
      "entries": [
        {
          "entries": [
            {
              "entries": [
                "You spent years learning the lore of the multiverse. You scoured manuscripts, studied scrolls, and listened to the greatest experts on the subjects that interest you. Your efforts have made you a master in your fields of study."
              ],
              "type": "entries"
            }
          ],
          "type": "entries"
        }
      ],
      "name": "Sage",
      "source": "PHB"
    }
  },
  {
    "basicRules": true,
    "entries": [
      {
        "items": [
          {
            "entry": "{@skill Athletics}, {@skill Intimidation}",
            "name": "Skill Proficiencies:",
            "type": "item"
          },
          {
            "entry": "One type of {@filter gaming set|items|source=phb|miscellaneous=mundane|type=gaming set}, {@filter vehicles (land)|items|source=phb;dmg|miscellaneous=mundane|type=vehicle (land)}",
            "name": "Tool Proficiencies:",
            "type": "item"
          },
          {
            "entry": "An insignia of rank, a trophy taken from a fallen enemy (a {@item dagger|phb}, broken blade, or piece of a banner), a bone {@item dice set|phb} or {@item playing card set|phb}, a set of {@item common clothes|phb}, and a belt {@item pouch|phb} containing 10 gp",
            "name": "Equipment:",
            "type": "item"
          }
        ],
        "style": "list-hang-notitle",
        "type": "list"
      },
      {
        "data": {
          "isFeature": true
        },
        "entries": [
          "You have a military rank from your career as a soldier. Soldiers loyal to your former military organization still recognize your authority and influence, and they defer to you if they are of a lower rank. You can invoke your rank to exert influence over other soldiers and requisition simple equipment or horses for temporary use. You can also usually gain access to friendly military encampments and fortresses where your rank is recognized."
        ],
        "name": "Feature: Military Rank",
        "type": "entries"
      },
      {
        "entries": [
          "During your time as a soldier, you had a specific role to play in your unit or army. Roll a d8 or choose from the options in the table below to determine your role:",
          {
            "colLabels": [
              "d8",
              "Role"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Officer"
              ],
              [
                "2",
                "Scout"
              ],
              [
                "3",
                "Infantry"
              ],
              [
                "4",
                "Cavalry"
              ],
              [
                "5",
                "Healer"
              ],
              [
                "6",
                "Quartermaster"
              ],
              [
                "7",
                "Standard-bearer"
              ],
              [
                "8",
                "Support staff (cook, blacksmith, or the like)"
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Specialty",
        "type": "entries"
      },
      {
        "entries": [
          "The horrors of war combined with the rigid discipline of military service leave their mark on all soldiers, shaping their ideals, creating strong bonds, and often leaving them scarred and vulnerable to fear, shame, and hatred.",
          {
            "colLabels": [
              "d8",
              "Personality Trait"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I'm always polite and respectful."
              ],
              [
                "2",
                "I'm haunted by memories of war. I can't get the images of violence out of my mind."
              ],
              [
                "3",
                "I've lost too many friends, and I'm slow to make new ones."
              ],
              [
                "4",
                "I'm full of inspiring and cautionary tales from my military experience relevant to almost every combat situation."
              ],
              [
                "5",
                "I can stare down a hell hound without flinching."
              ],
              [
                "6",
                "I enjoy being strong and like breaking things."
              ],
              [
                "7",
                "I have a crude sense of humor."
              ],
              [
                "8",
                "I face problems head-on. A simple, direct solution is the best path to success."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Ideal"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "Greater Good. Our lot is to lay down our lives in defense of others. (Good)"
              ],
              [
                "2",
                "Responsibility. I do what I must and obey just authority. (Lawful)"
              ],
              [
                "3",
                "Independence. When people follow orders blindly, they embrace a kind of tyranny. (Chaotic)"
              ],
              [
                "4",
                "Might. In life as in war, the stronger force wins. (Evil)"
              ],
              [
                "5",
                "Live and Let Live. Ideals aren't worth killing over or going to war for. (Neutral)"
              ],
              [
                "6",
                "Nation. My city, nation, or people are all that matter. (Any)"
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Bond"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "I would still lay down my life for the people I served with."
              ],
              [
                "2",
                "Someone saved my life on the battlefield. To this day, I will never leave a friend behind."
              ],
              [
                "3",
                "My honor is my life."
              ],
              [
                "4",
                "I'll never forget the crushing defeat my company suffered or the enemies who dealt it."
              ],
              [
                "5",
                "Those who fight beside me are those worth dying for."
              ],
              [
                "6",
                "I fight for those who cannot fight for themselves."
              ]
            ],
            "type": "table"
          },
          {
            "colLabels": [
              "d6",
              "Flaw"
            ],
            "colStyles": [
              "col-1 text-center",
              "col-11"
            ],
            "rows": [
              [
                "1",
                "The monstrous enemy we faced in battle still leaves me quivering with fear."
              ],
              [
                "2",
                "I have little respect for anyone who is not a proven warrior."
              ],
              [
                "3",
                "I made a terrible mistake in battle that cost many lives—and I would do anything to keep that mistake secret."
              ],
              [
                "4",
                "My hatred of my enemies is blinding and unreasoning."
              ],
              [
                "5",
                "I obey the law, even if the law causes misery."
              ],
              [
                "6",
                "I'd rather eat my armor than admit when I'm wrong."
              ]
            ],
            "type": "table"
          }
        ],
        "name": "Suggested Characteristics",
        "type": "entries"
      }
    ],
    "hasFluff": true,
    "name": "Soldier",
    "page": 140,
    "reprintedAs": [
      "Soldier|XPHB"
    ],
    "skillProficiencies": [
      {
        "athletics": true,
        "intimidation": true
      }
    ],
    "source": "PHB",
    "startingEquipment": [
      {
        "_": [
          {
            "special": "insignia of rank"
          },
          {
            "special": "trophy taken from a fallen enemy (a dagger, broken blade, or piece of a banner)"
          },
          "common clothes|phb",
          {
            "containsValue": 1000,
            "item": "pouch|phb"
          }
        ]
      },
      {
        "a": [
          {
            "displayName": "bone dice set",
            "item": "dice set|phb"
          }
        ],
        "b": [
          "playing card set|phb"
        ]
      }
    ],
    "toolProficiencies": [
      {
        "anyGamingSet": 1,
        "vehicles (land)": true
      }
    ],
    "id": 58,
    "fluff": {
      "entries": [
        {
          "entries": [
            {
              "entries": [
                "War has been your life for as long as you care to remember. You trained as a youth, studied the use of weapons and armor, learned basic survival techniques, including how to stay alive on the battlefield. You might have been part of a standing national army or a mercenary company, or perhaps a member of a local militia who rose to prominence during a recent war.",
                "When you choose this background, work with your DM to determine which military organization you were a part of, how far through its ranks you progressed, and what kind of experiences you had during your military career. Was it a standing army, a town guard, or a village militia? Or it might have been a noble's or merchant's private army, or a mercenary company."
              ],
              "type": "entries"
            }
          ],
          "type": "entries"
        }
      ],
      "name": "Soldier",
      "source": "PHB"
    }
  },
  {
    "_copy": {
      "_mod": {
        "entries": {
          "items": {
            "data": {
              "isFeature": true
            },
            "entries": [
              "You have a reliable and trustworthy contact who acts as your liaison to a network of other spies. You know how to get messages to and from your contact, even over great distances; specifically, you know the local messengers, corrupt caravan masters, and seedy sailors who can deliver messages for you."
            ],
            "name": "Feature: Spy Contact",
            "type": "entries"
          },
          "mode": "replaceArr",
          "replace": "Feature: Criminal Contact"
        }
      },
      "name": "Criminal",
      "source": "PHB"
    },
    "basicRules": true,
    "hasFluff": true,
    "name": "Variant Criminal (Spy)",
    "page": 130,
    "source": "PHB",
    "id": 60,
    "fluff": {
      "entries": [
        {
          "entries": [
            {
              "entries": [
                "Although your capabilities are not much different from those of a burglar or smuggler, you learned and practiced them in a very different context: as an espionage agent. You might have been an officially sanctioned agent of the crown, or perhaps you sold the secrets you uncovered to the highest bidder."
              ],
              "type": "entries"
            }
          ],
          "type": "entries"
        }
      ],
      "name": "Variant Criminal (Spy)",
      "source": "PHB"
    }
  }
] as const

// Named exports for convenience
export const acolyte = srdBackgrounds[0]
export const criminal = srdBackgrounds[1]
export const folkHero = srdBackgrounds[2]
export const noble = srdBackgrounds[3]
export const sage = srdBackgrounds[4]
export const soldier = srdBackgrounds[5]
export const variantCriminalSpy = srdBackgrounds[6]
