// Auto-generated SRD test fixtures — do not edit manually
// Generated by scripts/extract-srd-fixtures.py
// SRD content is published under the OGL

/* eslint-disable @typescript-eslint/no-explicit-any */
export const homebrewItems: Record<string, any>[] = [
  {
    "id": "hb-item-1",
    "name": "Blade of Testing",
    "source": "HB",
    "type": "M",
    "rarity": "rare",
    "reqAttune": true,
    "weight": 3,
    "weaponCategory": "martial",
    "dmg1": "1d8",
    "dmgType": "S",
    "bonusWeapon": "+1",
    "entries": [
      "You gain a +1 bonus to attack and damage rolls made with this magic weapon.",
      "When you hit with this weapon, the target takes an extra 1d6 radiant damage."
    ],
    "srd": false,
    "_isHomebrew": true
  },
  {
    "id": "hb-item-2",
    "name": "Amulet of Test Protection",
    "source": "HB",
    "type": "WN",
    "rarity": "uncommon",
    "reqAttune": true,
    "entries": [
      "While wearing this amulet, you gain a +1 bonus to AC and saving throws."
    ],
    "srd": false,
    "_isHomebrew": true
  },
  {
    "id": "hb-item-3",
    "name": "Potion of Test Healing",
    "source": "HB",
    "type": "P",
    "rarity": "common",
    "reqAttune": false,
    "entries": [
      "When you drink this potion, you regain 3d8 + 3 hit points."
    ],
    "srd": false,
    "_isHomebrew": true
  }
] as const

// Named exports for convenience
export const bladeofTesting = homebrewItems[0]
export const amuletofTestProtection = homebrewItems[1]
export const potionofTestHealing = homebrewItems[2]
