// Auto-generated SRD test fixtures — do not edit manually
// Generated by scripts/extract-srd-fixtures.py
// SRD content is published under the OGL

/* eslint-disable @typescript-eslint/no-explicit-any */
export const srdSubclasses: Record<string, any>[] = [
  {
    "className": "Barbarian",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Path of the Berserker",
    "page": 49,
    "reprintedAs": [
      "Berserker|Barbarian|XPHB|XPHB"
    ],
    "shortName": "Berserker",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Path of the Berserker|Barbarian||Berserker||3",
      "Mindless Rage|Barbarian||Berserker||6",
      "Intimidating Presence|Barbarian||Berserker||10",
      "Retaliation|Barbarian||Berserker||14"
    ],
    "id": 287
  },
  {
    "additionalSpells": [
      {
        "known": {
          "6": [
            {
              "choose": "level=0;1;2;3"
            },
            {
              "choose": "level=0;1;2;3"
            }
          ]
        },
        "name": "Additional Magical Secrets"
      }
    ],
    "className": "Bard",
    "classSource": "PHB",
    "edition": "classic",
    "name": "College of Lore",
    "page": 54,
    "reprintedAs": [
      "Lore|Bard|XPHB|XPHB"
    ],
    "shortName": "Lore",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "College of Lore|Bard||Lore||3",
      "Additional Magical Secrets|Bard||Lore||6",
      "Peerless Skill|Bard||Lore||14"
    ],
    "id": 337
  },
  {
    "additionalSpells": [
      {
        "prepared": {
          "1": [
            "bless",
            "cure wounds"
          ],
          "3": [
            "lesser restoration",
            "spiritual weapon"
          ],
          "5": [
            "beacon of hope",
            "revivify"
          ],
          "7": [
            "death ward",
            "guardian of faith"
          ],
          "9": [
            "mass cure wounds",
            "raise dead"
          ]
        }
      }
    ],
    "basicRules": true,
    "className": "Cleric",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Life Domain",
    "page": 60,
    "reprintedAs": [
      "Life|Cleric|XPHB|XPHB"
    ],
    "shortName": "Life",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Life Domain|Cleric||Life||1",
      "Channel Divinity: Preserve Life|Cleric||Life||2",
      "Blessed Healer|Cleric||Life||6",
      "Divine Strike|Cleric||Life||8",
      "Blessed Strikes|Cleric||Life||8|TCE",
      "Supreme Healing|Cleric||Life||17"
    ],
    "id": 275
  },
  {
    "additionalSpells": [
      {
        "known": {
          "1": {
            "_": [
              {
                "choose": "level=0|class=Druid"
              }
            ]
          }
        },
        "name": "Arctic",
        "prepared": {
          "3": [
            "hold person",
            "spike growth"
          ],
          "5": [
            "sleet storm",
            "slow"
          ],
          "7": [
            "freedom of movement",
            "ice storm"
          ],
          "9": [
            "commune with nature",
            "cone of cold"
          ]
        }
      },
      {
        "known": {
          "1": {
            "_": [
              {
                "choose": "level=0|class=Druid"
              }
            ]
          }
        },
        "name": "Coast",
        "prepared": {
          "3": [
            "mirror image",
            "misty step"
          ],
          "5": [
            "water breathing",
            "water walk"
          ],
          "7": [
            "control water",
            "freedom of movement"
          ],
          "9": [
            "conjure elemental",
            "scrying"
          ]
        }
      },
      {
        "known": {
          "1": {
            "_": [
              {
                "choose": "level=0|class=Druid"
              }
            ]
          }
        },
        "name": "Desert",
        "prepared": {
          "3": [
            "blur",
            "silence"
          ],
          "5": [
            "create food and water",
            "protection from energy"
          ],
          "7": [
            "blight",
            "hallucinatory terrain"
          ],
          "9": [
            "insect plague",
            "wall of stone"
          ]
        }
      },
      {
        "known": {
          "1": {
            "_": [
              {
                "choose": "level=0|class=Druid"
              }
            ]
          }
        },
        "name": "Forest",
        "prepared": {
          "3": [
            "barkskin",
            "spider climb"
          ],
          "5": [
            "call lightning",
            "plant growth"
          ],
          "7": [
            "divination",
            "freedom of movement"
          ],
          "9": [
            "commune with nature",
            "tree stride"
          ]
        }
      },
      {
        "known": {
          "1": {
            "_": [
              {
                "choose": "level=0|class=Druid"
              }
            ]
          }
        },
        "name": "Grassland",
        "prepared": {
          "3": [
            "invisibility",
            "pass without trace"
          ],
          "5": [
            "daylight",
            "haste"
          ],
          "7": [
            "divination",
            "freedom of movement"
          ],
          "9": [
            "dream",
            "insect plague"
          ]
        }
      },
      {
        "known": {
          "1": {
            "_": [
              {
                "choose": "level=0|class=Druid"
              }
            ]
          }
        },
        "name": "Mountain",
        "prepared": {
          "3": [
            "spider climb",
            "spike growth"
          ],
          "5": [
            "lightning bolt",
            "meld into stone"
          ],
          "7": [
            "stone shape",
            "stoneskin"
          ],
          "9": [
            "passwall",
            "wall of stone"
          ]
        }
      },
      {
        "known": {
          "1": {
            "_": [
              {
                "choose": "level=0|class=Druid"
              }
            ]
          }
        },
        "name": "Swamp",
        "prepared": {
          "3": [
            "darkness",
            "Melf's acid arrow"
          ],
          "5": [
            "water walk",
            "stinking cloud"
          ],
          "7": [
            "freedom of movement",
            "locate creature"
          ],
          "9": [
            "insect plague",
            "scrying"
          ]
        }
      },
      {
        "known": {
          "1": {
            "_": [
              {
                "choose": "level=0|class=Druid"
              }
            ]
          }
        },
        "name": "Underdark",
        "prepared": {
          "3": [
            "spider climb",
            "web"
          ],
          "5": [
            "gaseous form",
            "stinking cloud"
          ],
          "7": [
            "greater invisibility",
            "stone shape"
          ],
          "9": [
            "cloudkill",
            "insect plague"
          ]
        }
      }
    ],
    "className": "Druid",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Circle of the Land",
    "page": 68,
    "reprintedAs": [
      "Land|Druid|XPHB|XPHB"
    ],
    "shortName": "Land",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Circle of the Land|Druid||Land||2",
      "Land's Stride|Druid||Land||6",
      "Nature's Ward|Druid||Land||10",
      "Nature's Sanctuary|Druid||Land||14"
    ],
    "id": 329
  },
  {
    "basicRules": true,
    "className": "Fighter",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Champion",
    "optionalfeatureProgression": [
      {
        "featureType": [
          "FS:F"
        ],
        "name": "Fighting Style",
        "progression": {
          "10": 1
        }
      }
    ],
    "page": 72,
    "reprintedAs": [
      "Champion|Fighter|XPHB|XPHB"
    ],
    "shortName": "Champion",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Champion|Fighter||Champion||3",
      "Remarkable Athlete|Fighter||Champion||7",
      "Additional Fighting Style|Fighter||Champion||10",
      "Superior Critical|Fighter||Champion||15",
      "Survivor|Fighter||Champion||18"
    ],
    "id": 293
  },
  {
    "additionalSpells": [
      {
        "ability": "wis",
        "innate": {
          "11": {
            "daily": {
              "1": [
                "sanctuary"
              ]
            }
          }
        }
      }
    ],
    "className": "Monk",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Way of the Open Hand",
    "page": 79,
    "reprintedAs": [
      "Open Hand|Monk|XPHB|XPHB"
    ],
    "shortName": "Open Hand",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Way of the Open Hand|Monk||Open Hand||3",
      "Wholeness of Body|Monk||Open Hand||6",
      "Tranquility|Monk||Open Hand||11",
      "Quivering Palm|Monk||Open Hand||17"
    ],
    "id": 265
  },
  {
    "additionalSpells": [
      {
        "prepared": {
          "13": [
            "freedom of movement",
            "guardian of faith"
          ],
          "17": [
            "commune",
            "flame strike"
          ],
          "3": [
            "protection from evil and good",
            "sanctuary"
          ],
          "5": [
            "lesser restoration",
            "zone of truth"
          ],
          "9": [
            "beacon of hope",
            "dispel magic"
          ]
        }
      }
    ],
    "className": "Paladin",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Oath of Devotion",
    "page": 85,
    "reprintedAs": [
      "Devotion|Paladin|XPHB|XPHB"
    ],
    "shortName": "Devotion",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Oath of Devotion|Paladin||Devotion||3",
      "Aura of Devotion|Paladin||Devotion||7",
      "Purity of Spirit|Paladin||Devotion||15",
      "Holy Nimbus|Paladin||Devotion||20"
    ],
    "id": 313
  },
  {
    "className": "Ranger",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Hunter",
    "page": 93,
    "reprintedAs": [
      "Hunter|Ranger|XPHB|XPHB"
    ],
    "shortName": "Hunter",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Hunter|Ranger||Hunter||3",
      "Defensive Tactics|Ranger||Hunter||7",
      "Multiattack|Ranger||Hunter||11",
      "Superior Hunter's Defense|Ranger||Hunter||15"
    ],
    "id": 321
  },
  {
    "basicRules": true,
    "className": "Rogue",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Thief",
    "page": 97,
    "reprintedAs": [
      "Thief|Rogue|XPHB|XPHB"
    ],
    "shortName": "Thief",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Thief|Rogue||Thief||3",
      "Supreme Sneak|Rogue||Thief||9",
      "Use Magic Device|Rogue||Thief||13",
      "Thief's Reflexes|Rogue||Thief||17"
    ],
    "id": 271
  },
  {
    "className": "Sorcerer",
    "classSource": "PHB",
    "edition": "classic",
    "name": "Draconic Bloodline",
    "page": 102,
    "reprintedAs": [
      "Draconic|Sorcerer|XPHB|XPHB"
    ],
    "shortName": "Draconic",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "Draconic Bloodline|Sorcerer||Draconic||1",
      "Elemental Affinity|Sorcerer||Draconic||6",
      "Dragon Wings|Sorcerer||Draconic||14",
      "Draconic Presence|Sorcerer||Draconic||18"
    ],
    "id": 333
  },
  {
    "additionalSpells": [
      {
        "expanded": {
          "s1": [
            "burning hands",
            "command"
          ],
          "s2": [
            "blindness/deafness",
            "scorching ray"
          ],
          "s3": [
            "fireball",
            "stinking cloud"
          ],
          "s4": [
            "fire shield",
            "wall of fire"
          ],
          "s5": [
            "flame strike",
            "hallow"
          ]
        }
      }
    ],
    "className": "Warlock",
    "classSource": "PHB",
    "edition": "classic",
    "name": "The Fiend",
    "page": 109,
    "reprintedAs": [
      "Fiend|Warlock|XPHB|XPHB"
    ],
    "shortName": "Fiend",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "The Fiend|Warlock||Fiend||1",
      "Dark One's Own Luck|Warlock||Fiend||6",
      "Fiendish Resilience|Warlock||Fiend||10",
      "Hurl Through Hell|Warlock||Fiend||14"
    ],
    "id": 325
  },
  {
    "basicRules": true,
    "className": "Wizard",
    "classSource": "PHB",
    "edition": "classic",
    "name": "School of Evocation",
    "page": 117,
    "reprintedAs": [
      "Evoker|Wizard|XPHB|XPHB"
    ],
    "shortName": "Evocation",
    "source": "PHB",
    "srd": true,
    "subclassFeatures": [
      "School of Evocation|Wizard||Evocation||2",
      "Potent Cantrip|Wizard||Evocation||6",
      "Empowered Evocation|Wizard||Evocation||10",
      "Overchannel|Wizard||Evocation||14"
    ],
    "id": 305
  }
] as const

// Named exports for convenience
export const pathoftheBerserker = srdSubclasses[0]
export const collegeofLore = srdSubclasses[1]
export const lifeDomain = srdSubclasses[2]
export const circleoftheLand = srdSubclasses[3]
export const champion = srdSubclasses[4]
export const wayoftheOpenHand = srdSubclasses[5]
export const oathofDevotion = srdSubclasses[6]
export const hunter = srdSubclasses[7]
export const thief = srdSubclasses[8]
export const draconicBloodline = srdSubclasses[9]
export const theFiend = srdSubclasses[10]
export const schoolofEvocation = srdSubclasses[11]
