// Mimir Map Print Template - Single Page
// Renders a map image fit to a single page with optional token legend

#import "/_shared/styles.typ": *
#import "/_shared/components.typ": *
#import "/_shared/cutouts.typ": render-cutout-pages

// Document setup - landscape orientation for most maps
#set page(
  paper: "us-letter",
  flipped: true,  // Landscape
  margin: 0.5in,
)

// Helper to safely get nested data
#let get(obj, key, default: none) = {
  if obj != none and key in obj { obj.at(key) } else { default }
}

// =============================================================================
// DATA EXTRACTION
// =============================================================================

#let map-name = get(data, "name", default: "Map")
#let image-path = get(data, "image_path", default: none)
#let width-px = get(data, "width_px", default: 1000)
#let height-px = get(data, "height_px", default: 1000)
#let print-mode = get(data, "mode", default: "preview")
#let include-cutouts = get(data, "include_cutouts", default: false)
#let tokens = get(data, "tokens", default: ())

// Calculate aspect ratio
#let aspect-ratio = width-px / height-px

// Available space (accounting for margins and header)
#let available-width = 10in  // 11in page width - 1in margins
#let available-height = 7in  // 8.5in page height - 1in margins - header space

// Calculate image size to fit while maintaining aspect ratio
#let img-width = if aspect-ratio > (available-width / available-height) {
  available-width
} else {
  available-height * aspect-ratio
}

#let img-height = img-width / aspect-ratio

// =============================================================================
// MAP LAYOUT
// =============================================================================

// Header
#align(center)[
  #text(size: sizes.lg, weight: "bold")[#map-name]
  #v(spacing.xs)
  #text(size: sizes.sm, fill: colors.text-secondary)[
    #if print-mode == "preview" [Preview Mode] else [Play Mode (1" = 5ft)]
  ]
]

#v(spacing.md)

// Map image
#if image-path != none [
  #align(center)[
    #image(image-path, width: img-width, height: img-height, fit: "contain")
  ]
] else [
  #align(center)[
    #block(
      width: img-width,
      height: img-height,
      stroke: 1pt + colors.border,
      inset: spacing.lg,
    )[
      #align(center + horizon)[
        #text(fill: colors.text-secondary)[Map image not available]
      ]
    ]
  ]
]

// Token legend (if tokens exist)
#if tokens.len() > 0 [
  #v(spacing.lg)
  #line(length: 100%, stroke: 0.5pt + colors.border-light)
  #v(spacing.sm)

  #text(size: sizes.sm, weight: "bold")[Token Legend:]
  #h(spacing.md)

  #let token-items = tokens.enumerate().map(((idx, token)) => {
    let name = get(token, "name", default: "Unknown")
    let token-type = get(token, "token_type", default: "unknown")
    [(#(idx + 1)) #name (#token-type)]
  })

  #text(size: sizes.xs)[#token-items.join([ | ])]
]

// Page footer
#place(bottom + center)[
  #text(size: sizes.xs, fill: colors.text-secondary)[
    Generated by Mimir DM
  ]
]

// =============================================================================
// TOKEN CUTOUTS (Optional)
// =============================================================================

#if include-cutouts and tokens.len() > 0 [
  #render-cutout-pages(map-name, tokens)
]
