// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A campaign - the top-level container for D&D campaign data.
 */
export type Campaign = { 
/**
 * Unique campaign ID (UUID)
 */
id: string, 
/**
 * Campaign name
 */
name: string, 
/**
 * Optional description
 */
description: string | null, 
/**
 * ISO8601 timestamp when archived, NULL means active
 */
archived_at: string | null, 
/**
 * ISO8601 timestamp of creation
 */
created_at: string, 
/**
 * ISO8601 timestamp of last update
 */
updated_at: string, };
