// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A homebrew item belonging to a campaign.
 */
export type CampaignHomebrewItem = { id: string, campaign_id: string, name: string, item_type: string | null, rarity: string | null, data: string, cloned_from_name: string | null, cloned_from_source: string | null, created_at: string, updated_at: string, };
