// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A character - either a player character or NPC in a campaign.
 * This is the database model - use `CharacterResponse` for API responses with classes.
 */
export type Character = { 
/**
 * Unique character ID (UUID)
 */
id: string, 
/**
 * Campaign this character belongs to (optional - characters can exist without a campaign)
 */
campaign_id: string | null, 
/**
 * Character name
 */
name: string, 
/**
 * Whether this is an NPC (1) or PC (0)
 */
is_npc: number, 
/**
 * Player name (for PCs)
 */
player_name: string | null, 
/**
 * Race name (e.g., "Elf", "Human")
 */
race_name: string | null, 
/**
 * Race source (e.g., "PHB", "VGtM")
 */
race_source: string | null, 
/**
 * Background name (e.g., "Acolyte", "Criminal")
 */
background_name: string | null, 
/**
 * Background source (e.g., "PHB")
 */
background_source: string | null, strength: number, dexterity: number, constitution: number, intelligence: number, wisdom: number, charisma: number, cp: number, sp: number, ep: number, gp: number, pp: number, traits: string | null, ideals: string | null, bonds: string | null, flaws: string | null, role: string | null, location: string | null, faction: string | null, 
/**
 * ISO8601 timestamp of creation
 */
created_at: string, 
/**
 * ISO8601 timestamp of last update
 */
updated_at: string, };
