// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CharacterClass } from "./CharacterClass";
import type { CharacterProficiency } from "./CharacterProficiency";

/**
 * Character with classes included - used for API responses.
 */
export type CharacterResponse = { id: string, campaign_id: string | null, name: string, is_npc: number, player_name: string | null, race_name: string | null, race_source: string | null, background_name: string | null, background_source: string | null, strength: number, dexterity: number, constitution: number, intelligence: number, wisdom: number, charisma: number, cp: number, sp: number, ep: number, gp: number, pp: number, traits: string | null, ideals: string | null, bonds: string | null, flaws: string | null, role: string | null, location: string | null, faction: string | null, created_at: string, updated_at: string, 
/**
 * Character classes (populated from character_classes table)
 */
classes: Array<CharacterClass>, 
/**
 * Character proficiencies (populated from character_proficiencies table)
 */
proficiencies: Array<CharacterProficiency>, };
