// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A proficiency held by a character.
 */
export type CharacterProficiency = { 
/**
 * Unique ID (UUID)
 */
id: string, 
/**
 * Character who has this proficiency
 */
character_id: string, 
/**
 * Type of proficiency
 */
proficiency_type: string, 
/**
 * Name of the proficiency
 */
name: string, 
/**
 * Whether character has expertise (double proficiency)
 */
expertise: number, };
