// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A map in a campaign or module.
 */
export type Map = { 
/**
 * Unique ID (UUID)
 */
id: string, 
/**
 * Campaign this map belongs to
 */
campaign_id: string, 
/**
 * Module this map belongs to (optional - None for campaign-level maps)
 */
module_id: string | null, 
/**
 * Display name
 */
name: string, 
/**
 * Description or notes
 */
description: string | null, 
/**
 * Sort order within campaign/module
 */
sort_order: number, 
/**
 * Reference to the UVTT asset in blob storage
 */
uvtt_asset_id: string, 
/**
 * Initial lighting mode: bright, dim, or dark
 */
lighting_mode: string, 
/**
 * Whether fog of war is enabled
 */
fog_enabled: number, 
/**
 * ISO8601 timestamp of creation
 */
created_at: string, 
/**
 * ISO8601 timestamp of last update
 */
updated_at: string, };
