/**
 * Fixture loading helpers for Vitest.
 *
 * Provides typed lookups into the SRD fixture data generated by
 * scripts/extract-srd-fixtures.py. Avoids the need to import huge
 * fixture arrays directly — instead, grab exactly the items you need.
 *
 * Usage:
 *   import { findClass, findSpell, getTestCharacter } from '@tests/helpers/fixtures'
 *
 *   const fighter = findClass('Fighter')
 *   const fireball = findSpell('Fireball')
 *   const testFighter = getTestCharacter('test-fighter-champion-5')
 */

import {
  srdClasses,
  srdSubclasses,
  srdClassFeatures,
  srdSubclassFeatures,
  srdBackgrounds,
  srdRaces,
  srdItems,
  srdSpells,
  srdMonsters,
  testCharacters,
  homebrewItems,
} from '../fixtures'

// Re-export raw arrays for tests that need them
export {
  srdClasses,
  srdSubclasses,
  srdClassFeatures,
  srdSubclassFeatures,
  srdBackgrounds,
  srdRaces,
  srdItems,
  srdSpells,
  srdMonsters,
  testCharacters,
  homebrewItems,
}

// ─── Generic helpers ─────────────────────────────────────────────────────────

type Fixture = Record<string, unknown>

function findByName(items: Fixture[], name: string): Fixture {
  const item = items.find(
    (i) => (i.name as string).toLowerCase() === name.toLowerCase(),
  )
  if (!item) {
    const available = items.map((i) => i.name).join(', ')
    throw new Error(`Fixture not found: "${name}". Available: ${available}`)
  }
  return item
}

function findById(items: Fixture[], id: string | number): Fixture {
  const item = items.find((i) => i.id === id)
  if (!item) {
    throw new Error(`Fixture not found with id: ${id}`)
  }
  return item
}

function filterBy(items: Fixture[], key: string, value: unknown): Fixture[] {
  return items.filter((i) => i[key] === value)
}

// ─── Class lookups ───────────────────────────────────────────────────────────

export function findClass(name: string): Fixture {
  return findByName(srdClasses, name)
}

export function findSubclass(name: string): Fixture {
  return findByName(srdSubclasses, name)
}

export function findSubclassByClass(className: string): Fixture[] {
  return filterBy(srdSubclasses, 'className', className)
}

export function findClassFeatures(className: string): Fixture[] {
  return filterBy(srdClassFeatures, 'className', className)
}

export function findClassFeaturesAtLevel(className: string, level: number): Fixture[] {
  return srdClassFeatures.filter(
    (f) => f.className === className && (f.level as number) <= level,
  )
}

export function findSubclassFeatures(subclassName: string): Fixture[] {
  return filterBy(srdSubclassFeatures, 'subclassName', subclassName)
}

export function findSubclassFeaturesAtLevel(subclassName: string, level: number): Fixture[] {
  return srdSubclassFeatures.filter(
    (f) => f.subclassName === subclassName && (f.level as number) <= level,
  )
}

// ─── Background / Race lookups ───────────────────────────────────────────────

export function findBackground(name: string): Fixture {
  return findByName(srdBackgrounds, name)
}

export function findRace(name: string): Fixture {
  return findByName(srdRaces, name)
}

// ─── Item lookups ────────────────────────────────────────────────────────────

export function findItem(name: string): Fixture {
  return findByName(srdItems, name)
}

export function findItemsByType(itemType: string): Fixture[] {
  return filterBy(srdItems, '_itemType', itemType)
}

export function findItemsByRarity(rarity: string): Fixture[] {
  return filterBy(srdItems, '_rarity', rarity)
}

// ─── Spell lookups ───────────────────────────────────────────────────────────

export function findSpell(name: string): Fixture {
  return findByName(srdSpells, name)
}

export function findSpellsByLevel(level: number): Fixture[] {
  return filterBy(srdSpells, '_level', level)
}

export function findSpellsBySchool(school: string): Fixture[] {
  return filterBy(srdSpells, '_school', school)
}

// ─── Monster lookups ─────────────────────────────────────────────────────────

export function findMonster(name: string): Fixture {
  return findByName(srdMonsters, name)
}

export function findMonstersByCR(cr: string): Fixture[] {
  return filterBy(srdMonsters, '_cr', cr)
}

export function findMonstersByType(creatureType: string): Fixture[] {
  return filterBy(srdMonsters, '_creatureType', creatureType)
}

// ─── Test character lookups ──────────────────────────────────────────────────

export function getTestCharacter(id: string): Fixture {
  return findById(testCharacters, id)
}

export function getTestCharacterByName(name: string): Fixture {
  return findByName(testCharacters, name)
}

export function getAllTestCharacters(): Fixture[] {
  return [...testCharacters]
}

// ─── Homebrew lookups ────────────────────────────────────────────────────────

export function getHomebrewItem(name: string): Fixture {
  return findByName(homebrewItems, name)
}

export function getAllHomebrewItems(): Fixture[] {
  return [...homebrewItems]
}

// ─── Bulk setup helpers ──────────────────────────────────────────────────────

/**
 * Build a class data lookup map keyed by lowercase class name,
 * matching the format used by CharacterSheetView's `classData` ref.
 */
export function buildClassDataMap(classNames?: string[]): Record<string, Fixture> {
  const names = classNames ?? srdClasses.map((c) => c.name as string)
  const map: Record<string, Fixture> = {}
  for (const name of names) {
    try {
      map[name.toLowerCase()] = findClass(name)
    } catch {
      // skip if not found
    }
  }
  return map
}

/**
 * Build a subclass data lookup map keyed by lowercase subclass name.
 */
export function buildSubclassDataMap(subclassNames?: string[]): Record<string, Fixture> {
  const names = subclassNames ?? srdSubclasses.map((s) => s.name as string)
  const map: Record<string, Fixture> = {}
  for (const name of names) {
    try {
      map[name.toLowerCase()] = findSubclass(name)
    } catch {
      // skip if not found
    }
  }
  return map
}
